package entity;
// Generated Jan 20, 2021 12:22:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String fname;
     private String lname;
     private String email;
     private String password;
     private Date createdAt;
     private Byte activeStatus;
     private Byte onlineStatus;
     private Set msgsForReceiverId = new HashSet(0);
     private Set msgsForSenderId = new HashSet(0);

    public User() {
    }

    public User(String fname, String lname, String email, String password, Date createdAt, Byte activeStatus, Byte onlineStatus, Set msgsForReceiverId, Set msgsForSenderId) {
       this.fname = fname;
       this.lname = lname;
       this.email = email;
       this.password = password;
       this.createdAt = createdAt;
       this.activeStatus = activeStatus;
       this.onlineStatus = onlineStatus;
       this.msgsForReceiverId = msgsForReceiverId;
       this.msgsForSenderId = msgsForSenderId;
    }

    public User(String fname, String lname, String email, String password, Date createdAt, Byte activeStatus, Byte onlineStatus) {
        this.fname = fname;
        this.lname = lname;
        this.email = email;
        this.password = password;
        this.createdAt = createdAt;
        this.activeStatus = activeStatus;
        this.onlineStatus = onlineStatus;
    }

//    public User(String fname, String lname, String email, String password, Date date, byte b, byte b0) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
    
    
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Byte getActiveStatus() {
        return this.activeStatus;
    }
    
    public void setActiveStatus(Byte activeStatus) {
        this.activeStatus = activeStatus;
    }
    public Byte getOnlineStatus() {
        return this.onlineStatus;
    }
    
    public void setOnlineStatus(Byte onlineStatus) {
        this.onlineStatus = onlineStatus;
    }
    public Set getMsgsForReceiverId() {
        return this.msgsForReceiverId;
    }
    
    public void setMsgsForReceiverId(Set msgsForReceiverId) {
        this.msgsForReceiverId = msgsForReceiverId;
    }
    public Set getMsgsForSenderId() {
        return this.msgsForSenderId;
    }
    
    public void setMsgsForSenderId(Set msgsForSenderId) {
        this.msgsForSenderId = msgsForSenderId;
    }




}


